name: Build IPA

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ldid
          
      - name: Make script executable
        run: chmod +x ipabuild.sh

      - name: Build IPA
        run: ./ipabuild.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MB-Bank-Fake-IPA
          path: noti.tipa
